### ISSUE TITLE
how to do default props?

### ISSUE THREAD

**Issue by tsiq-swyx** [strothj/react-docgen-typescript-webpack-plugin#5]
hello! i have a very basic question... how do i make default props show up in here?

![image](https://user-images.githubusercontent.com/35976578/36114788-096578a2-0fff-11e8-8e92-269fbd44fb2e.png)

[the styledguidist folks](https://github.com/styleguidist/react-docgen-typescript) dont document this either and i was just hoping for a pointer!

thank you again!

**Comment by strothj** [comment]
Hello,

There was an oversight on my part. I need to fix the plugin to support it. The loader version supports it.

In the prop description:
```typescript
interface Props {
  /**
    * @default green
    */
  color?: "blue" | "green";
}
```

**Comment by tsiq-swyx** [comment]
ok so if i read that right this is something to fix as I currently don't see this working in my version. i'll leave this issue open in case you want to track it. thanks again, you're awesome

**Comment by strothj** [comment]
I've uploaded v1.1 that has the support.

**Comment by tsiq-swyx** [comment]
yes!!

![image](https://user-images.githubusercontent.com/35976578/36164382-2ca58e4a-10ba-11e8-97a1-5887dad4f3db.png)

![image](https://user-images.githubusercontent.com/35976578/36164394-367b35b4-10ba-11e8-9758-d68130d2c0e3.png)

**Comment by city41** [comment]
Will default values always be surrounded by quotes? I feel for the above `delay1`, the default value shoudl be `250`, not `"250"`. Is it possible to accomplish that?

**Comment by strothj** [comment]
@city41 I opened a new issue to track this. I don't like those quotes either.

**Comment by ffloyd** [comment]
I'm also very interested in ability that @GabrielDuarteM mentioned.

Without it I'm forced to violate Don't Repeat Yourself principle because I have to write same value in two places. In such circumstances It's too easy to change values in the code but forget to change it in documentations. Especially for components with significant amount of props.

Situation may get even worse if you have some props interface which is built from extending another interface. With functional components I'm defining defaults inside function signature (it's most natural way for me). When doing this default in docstring and function signature inside different files.

Moreover, some people like to store types (and proptypes) inside separate from component's one file.
